### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by csdaraujo** [giggsey/libphonenumber-for-php#118]
Comparing the 55 file from Google and here we can see that our port is missing many phones from Brazil:
[https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/pt/55.txt](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/pt/55.txt)
[https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/geocoding/data/pt/55.php](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/geocoding/data/pt/55.php)

I'm trying to figure out what's wrong with GeneratePhonePrefixData.php. Maybe someone is faster than me :)

Cheers,
Caetano

**Comment by giggsey** [comment]
Thanks for noticing this.

If the entry is the same as the English version, it won't store it. At runtime, if there isn't a local version, it will fallback to English.

For example,

For the 'PT' file, 55613201 is Brasília - DF ([Source](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/pt/55.txt#L9883))
In the 'EN' file, 55613201 is also Brasília - DF ([Source](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/55.txt#L9885))

[Example number demo](http://libphonenumber-for-php.giggsey.net/?phonenumber=556132010000&country=BR&language=pt&region=)

So the functionality is working fine. However, it is still a bug that it is writing that array key in that array key in the first place and wasting memory/storage.

**Comment by giggsey** [comment]
Okay, I've had a change to look at this in more depth.

These rows are empty, because the leading prefix 5561 is different in English (5561|Federal District) and Portuguese (5561|Distrito Federal).

When an entry in the mapping file is an empty string (or null), it then looks up the same value in English. If the array key doesn't exist at all, it'll continue searching for a prefix.

I'm going to close this, as having the values as empty strings actually provides a performance benefit (there is no need to always search English).
