### ISSUE TITLE
Strategy to reduce number of file for a specific country / region

### ISSUE THREAD

**Issue by Indigo744** [giggsey/libphonenumber-for-php#140]
Hello,

I wonder if it would be possible to remove certain file for region I know I will not use?

For instance, I have a project where I know that all numbers will be either French, Swiss or Belgian. 
What can I do in order to remove all unnecessary files (e.g. chinese numbers, ...)?
Will it be a problem?

This would help reduce drastically the number of file in this library.
I know you are aware of this, as I can see in #121. But I want to go even further for my specific needs.

Thanks a lot for your answer.

**Comment by giggsey** [comment]
You could manually remove the files, and update any Map files to reflect the new state, but it would be a rather manual process.

The other approach would be to modify the build script to only include certain regions, and maintain a fork.

**Comment by Indigo744** [comment]
For option 1, I can imagine a composer post-update script that will remove unwanted file, right?
However, I don't see exactly what kind of file I can delete. Which Map file should I update?

Regarding option 2, do you have any pointers on how to modify the build process?

Thanks a lot for your answer! Love your work ;-)

**Comment by giggsey** [comment]
Option 1:

For the main metadata, the list of supported regions is loaded from [CountryCodeToRegionCodeMap](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/CountryCodeToRegionCodeMap.php). If you remove any of the main metadata files from data/, then you should tidy up the array too (otherwise it might try to load a missing metadata file).

For the prefix based systems (Geocoding, Carrier etc.), the directories contain a Map.php file. This lists the supported regions + prefix files. Again, if you delete the metadata file, then make sure you delete the entry from the array.


Option 2:

For the main metadata, it loads all the data from one xml file. It processes this in a [loop in BuildMetadataFromXML](https://github.com/giggsey/libphonenumber-for-php/blob/master/build/libphonenumber/buildtools/BuildMetadataFromXml.php#L103-L114). For the prefix mapper (geocoding, carrier etc.), then look in [GeneratePhonePrefixData](https://github.com/giggsey/libphonenumber-for-php/blob/master/build/libphonenumber/buildtools/GeneratePhonePrefixData.php#L54-L68). From memory, `$textFile` contains the source file name (en/44.txt, fr/41.txt etc.) and `$outputFiles` contains the array of files to write.

By filtering these functions by the regions you care about, it'll only write those files. I suggest still using phing to compile the data (it handles removing the old files first).


Option 2 would be easier going forward, as you would be able to keep the metadata/code changes up to date easier than manually removing files.

**Comment by Indigo744** [comment]
Thanks a lot for your pointers.

Actually, I only deleted files from data/ and geocoding, and it seems to work fine with all tested phones (fr, be, ch ...). So I guess it will do!
I use a post-update script with composer to remove the file I don't want.

I will close this thread, thanks a lot.

**Comment by giggsey** [comment]
Deleting the data files is fine, it's just that the library might throw an exception if it can't load the file. Although I guess it'll throw an exception if you try to use a region that doesn't exist, so it won't make much of a difference.

Regardless, glad you were able to sort something out.

**Comment by Indigo744** [comment]
Yes, and I surrounded each of my libphonenumber call with try/catch, so any error will be muted (and logged, for further analysis).
Since I use it primarily for formatting purpose, the risk is really low to have any problem.
Thanks again, appreciate your work and effort to bring this library into the PHP world!
