### ISSUE TITLE
E164 should not include extension number

### ISSUE THREAD

**Issue by RubenKruiswijk** [giggsey/libphonenumber-for-php#152]
I've found a discrepancy between the original libphonenumber implementation and this one regarding the handling of the extension for the E164 format.

https://libphonenumber.appspot.com/phonenumberparser?number=%2B1-907-486-4171+ex.+101&country=US&geocodingLocale=en-US
E164: ``+19074864171``

https://giggsey.com/libphonenumber/index.php?phonenumber=%2B1-907-486-4171+ext.+101&country=US&language=en&region=US
E164: ``+19074864171 ext. 101``

**Comment by giggsey** [comment]
Thanks for reporting.

It looks like this bug has existed since 2012/2013.

Once Google release their next version (I believe they are aiming for this week), then a new version will be tagged here. The Release Notes will mention this change, as some people might be relying on formatting to E164 to output extensions.

**Comment by RubenKruiswijk** [comment]
Boss! Thanks!
