### ISSUE TITLE
00 isn't converted to + if defaultRegion is missing

### ISSUE THREAD

**Issue by OlaviSau** [giggsey/libphonenumber-for-php#176]
Plus is accepted as the international prefix, but 00 is not. 
> The International Telecommunication Union (ITU) recommends the sequence 00 as a standard for an international call prefix, and this has been implemented by many countries, but not all of them.[2] Some countries use the 00 prefix which is followed by the international carrier code.

```
\libphonenumber\PhoneNumberUtil::getInstance()->parse('00 61 1900 654 321', ''); //=> @throw \libphonenumber\NumberParseException
```

```
...
// Check the region supplied is valid, or that the extracted number starts with some sort of +
// sign so the number's region can be determined.
if ($checkRegion && !$this->checkRegionForParsing($nationalNumber, $defaultRegion)) {
    throw new NumberParseException(
        NumberParseException::INVALID_COUNTRY_CODE, 
        "Missing or invalid default region."
    );
}
...
static::$PLUS_CHARS_PATTERN = "[" . static::PLUS_CHARS . "]+";
...
 if (!$this->isValidRegionCode($defaultRegion)) {
            // If the number is null or empty, we can't infer the region.
            $plusCharsPatternMatcher = new Matcher(static::$PLUS_CHARS_PATTERN, $numberToParse);
            if ($numberToParse === null || mb_strlen($numberToParse) == 0 || !$plusCharsPatternMatcher->lookingAt()) {
                return false;
            }
        }
...
```

**Comment by giggsey** [comment]
You hit the nail on the head with the quote.

> this has been implemented by many countries, but not all of them.

libphonenumber can't know that 00 is the International Dialling Prefix, because it depends on the region, which is why you need to pass it. The only universal International Dialling Prefix is the +.

Google's demo does the same thing: https://libphonenumber.appspot.com/phonenumberparser?number=00+61+1900+654+321

I'm going to close this, as it's not a valid bug for the PHP port, but rather the behaviour of Google's library. If you think that's incorrect behaviour, either [open an Issue](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue) with them, or post to their [mailing list](https://groups.google.com/group/libphonenumber-discuss).
