### ISSUE TITLE
Number Detection doesn't work

### ISSUE THREAD

**Issue by Phillipip** [giggsey/libphonenumber-for-php#178]
The Number +551997945216 for example doesn't found. But this is a correct number: https://www.numberingplans.com/?page=analysis&sub=phonenr

**Comment by giggsey** [comment]
Hi,

This port of libphonenumber returns the same as Google's version: https://libphonenumber.appspot.com/phonenumberparser?number=%2B551997945216

Therefore, I'm closing this, as it's not an issue with this library. See the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for future details.

**Comment by lgaitan** [comment]
The number "+551997945216" is no longer valid since august 2013.

All brazilian phone numbers contain a leading number nine, so your number should be "+55 19 997945216".
https://libphonenumber.appspot.com/phonenumberparser?number=%2B5519997945216

Some code areas are still migrating from the old numbering system.

**Comment by Phillipip** [comment]
Thank you for this answer!
