### ISSUE TITLE
Unknown type instead of mobile from French numbers

### ISSUE THREAD

**Issue by Robinouh** [giggsey/libphonenumber-for-php#271]
Hi,

I found a bug in the library.

The type of French mobile numbers beginning with "07" is "UNKNOWN" when it should be "MOBILE".

Reference: [https://en.wikipedia.org/wiki/Telephone_numbers_in_France](https://en.wikipedia.org/wiki/Telephone_numbers_in_France)

Best regards.

**Comment by giggsey** [comment]
Do you have an example number that you've run against the demo?

According to the metadata, French mobile numbers can start with 6, or 73-79.

**Comment by Robinouh** [comment]
The French mobile numbers beginning with "07" are used since May 3, 2010 to answer the shortage of mobile numbers beginning with "06".

I did some tests with the following code that returns `10` instead of `1`.
```
$number = PhoneNumber::parse("+33712345678");
echo $number->getNumberType();
```

**Comment by giggsey** [comment]
If I run that example number through [Google's demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B33712345678) it returns an invalid number (which is why you get type = UNKNOWN).

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for issues with metadata.
