### ISSUE TITLE
Why is getNumberTypeHelper() protected?

### ISSUE THREAD

**Issue by mwargan** [giggsey/libphonenumber-for-php#335]
Hey! I'm just curious to why `getNumberTypeHelper()` is protected; if it weren't we could easily get the text/string type for the int returned by `getNumberType()`, or is there another way to get the actual string number type that I'm completely missing?

**Comment by giggsey** [comment]
`getNumberTypeHelper()` is protected because it's not part of the public API on Google's project. If I made it public here, and Google changed how it worked upstream, then that would cause issues with semantic versioning here.

As for getting the actual string version of PhoneNumberType, it's integers because PHP doesn't natively support ENUMs. There isn't anything in the library to convert it into the actual string. Whenever I've needed it (the demo & other projects), I've just written a simple switch myself. I could see it being useful to have that function as part of the PhoneNumberType class.

**Comment by giggsey** [comment]
I've just realised there is a values() function on PhoneNumberType, which returns an associative array of the int => string representation.

That should provide the functionality required.

I'm going to close this issue. If Google change the `getNumberTypeHelper()` function, then the same changes will be made on this PHP version.
