### ISSUE TITLE
Try to resolve missing country code digit, Could not interpret numbers after plus-sign.

### ISSUE THREAD

**Issue by TechOverflow** [giggsey/libphonenumber-for-php#419]
The Czech Republic has a prefix of `+420`, while Slovakia has `+421`.
Some users unfortunately omit the 0, eg. `+42777111222` instead of `+420777111222`.
Is there a way to "try" adding the zero for countries that use a zero as their third prefix digit?
Currently, when I try to check a number like this, I get `Could not interpret numbers after plus-sign.`

**Comment by giggsey** [comment]
If they are only entering the national number (777111222), then getting the default country code to either CZ or SK could allow you to parse it for each respective country.

Otherwise, I think your approach is currently the best option you have. Try to validate it without the zero on the country code, and add it back in if the validation fails. Probably worth checking with the end user the final number, just in case they didn't mean a Czech Republic number.

**Comment by TechOverflow** [comment]
Thanks!
