### ISSUE TITLE
PhoneNumberOfflineGeocoder Results

### ISSUE THREAD

**Issue by RobertEcker** [giggsey/libphonenumber-for-php#511]
https://github.com/google/libphonenumber shows the (correct) town
https://github.com/giggsey/libphonenumber-for-php shows only the correct country but not the town

**Comment by giggsey** [comment]
Hi,

Can you please provide an example?

**Comment by RobertEcker** [comment]
Hi,
sure:

https://libphonenumber.appspot.com/phonenumberparser?number=%2B437752812345
versus
https://giggsey.com/libphonenumber/?phonenumber=437752812345&country=AT&language=de&region=de

**Comment by giggsey** [comment]
If you pass the same parameters in, you get the same result: https://giggsey.com/libphonenumber/?phonenumber=%2B437752812345

The difference in result is because you're passing in a different region to the phone number, so it only resolves to the country instead of the town.

See https://github.com/giggsey/libphonenumber-for-php/blob/9f0b2147588f548a9382b89b59acd78172d49f7b/src/geocoding/PhoneNumberOfflineGeocoder.php#L176

**Comment by RobertEcker** [comment]
Thank you very much for clarification
