### ISSUE TITLE
German geocoding data incomplete

### ISSUE THREAD

**Issue by thomaschaaf** [giggsey/libphonenumber-for-php#69]
Looking at: https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/geocoding/data/de/49.php

contains way less data then:
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/de/49.txt

Why is this?

**Comment by giggsey** [comment]
I've just run the compile command again, and it has not picked up on any changes.

The way the Prefix File Reader (used by the Geolocation, PhoneNumberToCarrierMapper and PhoneNumberToTimeZonesMapper) is by reading from the requested language first, then then falling back to English.

When compiling the data, it uses this fallback in order to save space, and 'compress' the amount of data stored in PHP. As the majority of the entries in [de/49.txt](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/de/49.txt) are the same as [en/49.txt](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/49.txt), it only writes them once (in the English file).

The few differences you see in [de/49.php](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/geocoding/data/de/49.php) are either not present in the English version, or different (e.g. 4935753 in English is `Grossräschen`, but the same prefix in German is `Großräschen`).

**Comment by thomaschaaf** [comment]
It actually worked as expected. Sorry :(

**Comment by giggsey** [comment]
No problem, glad I was able to explain it
